name = "CliMADatasets"
uuid = "49523d62-8978-4391-abdd-b8467d4505ae"
authors = ["Climate Modeling Alliance"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
